---
# Which user get which ssh key:
users:
  l3d:
   - l3d@backup.l3d.yt
   - l3d@derpy.l3d.yt
   - l3d@mobile.l3d.yt
   - l3d@pinkie.l3d.yt
   - l3d@business.wingcon.com
   - l3d@backup-rsa.l3d.yt
  alex:
   - alex@toolbox
   - alex@rsa-toolbox
   matt:
   - matt@toolbox20_id_ed22519.pub

# admins on local device:
admins:
  - l3d
  - alex
  - matt

# users createt on this host
accounts:
  - l3d
  - alex
  - matt

ssh_public_key_store: 'admin_ssh_keys'
only_allow_ed25519: true
