---
# Which user get which ssh key:
users:
  l3d:
   - l3d@backup.l3d.yt
   - l3d@derpy.l3d.yt
   - l3d@mobile.l3d.yt
   - l3d@pinkie.l3d.yt
   - l3d@business.wingcon.com
  alex:
   - alex@toolbox

# admins on local device:
admins:
  - l3d
  - alex
# users createt on this host
accounts:
  - l3d
  - alex

ssh_public_key_store: 'admin_ssh_keys'
home_sweet_home: false
only_allow_ed25519: false
add_ethz: false
restrict_allow_users: false
sshd_password_authentication: 'no'


