---

# Authorisation via ssh:
users:
  l3d:
   - l3d
  mart:
   - mart

# admins on local device:
admins:
  - mart
  - l3d

# basic system variable
hostname: "starswirl.tbbs.me"


# configure resolveer role
resolver_searchdomains:
  - tbbs.me

resolver_nameservers:
  - 85.214.20.141
  - 194.150.168.168
  - 2001:1608:10:25::1c04:b12f
  - 2001:41d0:2:73d4::125
  - 2a02:2970:1002::18

# ansible managed warning
ansible_managed: "This file is managed by ansible - to change any variable here, please remeber they will be overwritten! -> More information: https://github.com/ToolboxBodensee/toolbox-netzwerk.git "

# some network details for unbound:
unbound_accepted_ip: 
  - "2003:a:13b:9000::/56"
  - "2003:1:17f:bb90::/64"
  - "172.23.16.0/16"
  - "217.91.187.203/32"

unbound_interfaces:
  - "172.23.16.1"
  - "2003:a:13b:9000::1"

# some variables for isc-dhcp-server

ipv4_dhcp_interface: enp1s0

dhcp:
  - pool: '172.23.16.0'
  - mask: '255.255.240.0'
  - range: '172.23.16.100 172.23.30.255'
  - router: '172.23.16.1'
  - dnsv4: '172.23.16.1'
  - domain: 'tbbs.me'
  - broadcast: '172.23.31.255'
  - lease: '14400'
  - max_lease: '1823442'
  - unify: '172.23.16.1'

# Ansible-Vault encrypted username and password for pppoe:
pppoe_username: "{{ _pppoe_username | string }}"
pppoe_passwort: "{{ _pppoe_passwort | string }}"

_pppoe_username: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35303534626662353838636162346630373634313164356461323961333166336433373037306437
          6234343330326430636365613561643462366634303234350a623261366139666339363964613734
          39306661383164656163623763363565356235643762363835643962373133663865326334636662
          6265393336656364310a373461626139616331336532313237636233306139383739333965616230
          31353239633436303166306362373036613936316632613530346538616665323031303965373961
          6664663830353534363034633964636137333635646233383632
_pppoe_passwort: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30643533356138396561376661633737363166386435326633316630366564353537653539303261
          6331303238313566626139653763376265653731616261630a393232653739303763366263623639
          32366238326133613362343664616433323566386338613366376365316537373438386633623339
          3662373361326532660a356132313832396630643534353039633930393533343762346562333031
          3033

static_pppoe_ipv4: "217.91.187.203"

# some dsl-provider config vars:
default_pppoe_pty: "/usr/sbin/pppoe -I enp3s0.7 -T 80 -m 1452"
use_pppoe_ns: false
install_pppoe_route: true

# Which interface is used by pppoe
pppoe_interface: "enp3s0.7"
use_pppoe_plugin: true

